location: ${LOCATION}

logger:
  level: ${LOGGER_LEVEL}
  encoding: ${LOGGER_ENCODING}

db:
  dsn: ${DB_DSN}

server:
  grpc_port: 18080
  http_port: 8080
  use_tls: false
  max_send_message_length: 54760833024
  max_receive_message_length: 54760833024
