version: '3.8'

volumes:
  todo_vol:

services:
  todo_app:
    ports:
      - "8080:8080"
      - "18080"
    build:
      context: ../..
      dockerfile: Dockerfile
      target: app
    volumes:
      - ./../../:/app:rw
    environment:
      ENV_FILE: ./.env
    depends_on: [todo_db]

  todo_db:
    image: postgres:15.0
    restart: always
    volumes:
      - todo_vol:/var/lib/postgresql/data
      - ../../migrations:/migrations
    environment:
      POSTGRES_USER: todo
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: todo
      POSTGRES_DATABASE: todo
    ports:
      - "5490:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "todo" ]
      interval: 5s
      timeout: 1s
      retries: 2
