version: '3.8'

volumes:
  todo_vol:

services:

  todo_migrate:
    restart: on-failure
    image: migrate/migrate
    volumes:
      - ../../migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://todo:todo@todo_db:5432/todo?sslmode=disable", "up" ]
    depends_on:
      todo_db:
        condition: service_healthy

  todo_app:
    ports:
      - "8080:8080"
      - "18080"
    build:
      context: ./../../
      dockerfile: ./ops/docker/Dockerfile
      target: application
    volumes:
      - ./../../:/app:rw
    environment:
      ENV_FILE: ./../.env

  todo_db:
    image: postgres:15.0
    restart: always
    volumes:
      - todo_vol:/var/lib/postgresql/data
      - ../../migrations:/migrations
    environment:
      POSTGRES_USER: todo
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: todo
      POSTGRES_DATABASE: todo
    ports:
      - "5490:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "todo" ]
      interval: 5s
      timeout: 1s
      retries: 2
